# Site-specific overrides for Butterfly 5.7.

menu:
  Home: / || fas fa-home
  Archives: /archives/ || fas fa-archive
  Log: /log || fas fa-book
  Tags: /tags/ || fas fa-tags
  Categories: /categories/ || fas fa-folder-open
  List||fas fa-list||hide:
    Gallery: /Gallery/ || fa fa-camera-retro
    Map: /Map/ || fa fa-map-signs
  Link: /link/ || fas fa-link
  About: /about/ || fas fa-heart

code_blocks:
  theme: light
  macStyle: true
  height_limit: false
  word_wrap: false
  copy: true
  language: true
  shrink: true
  fullpage: false

social:
  fab fa-github: https://github.com/ZiHao256 || Github
  fa fa-rss: /atom.xml || RSS
  fa-brands fa-google: mailto:zihao626@gmail.com || Gmail
  fa fa-graduation-cap: mailto:zh_ma@stu.xidian.edu.cn || XDU Mail

favicon: https://github.com/ZiHao256/ZiHao256.github.io/blob/hexo/images/stitch.JPG?raw=true

avatar:
  img: https://github.com/ZiHao256/ZiHao256.github.io/blob/hexo/images/stitch.JPG?raw=true
  effect: false

index_img: https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/john-towner-3Kv48NS4WUU-unsplash.jpg
default_top_img: https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/john-towner-3Kv48NS4WUU-unsplash.jpg
index_top_img_height: 400px

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/in-the-early-morning-of-forest-wallpaper.jpeg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/star_sky.webp
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/beautiful-milky-way-night-sky.webp
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/drain.webp
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/high-angle-shot-beautiful-forest-with-lot-green-trees-enveloped-fog-new-zealand.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/john-towner-3Kv48NS4WUU-unsplash.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/joseph-barrientos-oQl0eVYd_n8-unsplash.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/narrow-muddy-road-dark-forest.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/pathway-middle-green-leafed-trees-with-sun-shining-through-branches.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/sebastian-unrau-sp-p7uuT0tw-unsplash.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/steven-kamenar-MMJx78V7xS8-unsplash.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven1.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven2.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven4.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven5.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven6.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven7.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven8.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven9.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven13.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven-1pr8q9.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven-4ggvml.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven-gpdvj3.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven-kxd1md.jpg
    - https://raw.githubusercontent.com/ZiHao256/ZiHao256.github.io/hexo/images/wallhaven-yx7vmk.jpg

error_404:
  enable: true
  subtitle: Page Not Found
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

post_meta:
  page:
    date_type: both
    date_format: relative
    categories: true
    tags: true
    label: true
  post:
    position: left
    date_type: both
    date_format: relative
    categories: true
    tags: true
    label: true

toc:
  post: true
  page: false
  number: false
  expand: false
  style_simple: false
  scroll_percent: true

photofigcaption: true

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

search:
  use: local_search
  local_search:
    preload: true
    top_n_per_article: 1
    unescape: false
    pagination:
      enable: false
      hitsPerPage: 8

comments:
  use: Gitalk
  text: true
  lazyload: false
  count: true
  card_post_count: false

gitalk:
  enable: true
  owner: ZiHao256
  admin: ZiHao256
  client_id: 3b2ff3959cccdea73272
  client_secret: ff54cd4f8d455c066e787ca2dc1684a21094e488
  repo: ZiHao256.github.io
  option:
  distractionFreeMode: true
  labels: 'gitalk'


footer:
  owner:
    enable: true
    since: 2021
  copyright:
    enable: true
    version: true
  custom_text: Hi, welcome to my <a href="https://zihao256.github.io/">Blog</a>!

aside:
  card_author:
    button:
      link: https://github.com/ZiHao256
  card_announcement:
    content: keep moving in 2024
  card_newest_comments:
    enable: true
  card_webinfo:
    runtime_date: 4/16/2021 00:00:00

translate:
  enable: true
  default: 简
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: 繁
  msgToSimplifiedChinese: 簡

preloader:
  enable: true
  source: 1

beautify:
  enable: true
  field: site
  title_prefix_icon: "\\f0c1"
  title_prefix_icon_color: "#F47466"

canvas_fluttering_ribbon:
  enable: true
  mobile: false

click_heart:
  enable: true
  mobile: true

lightbox: fancybox

pjax:
  enable: true

inject:
  head:
    - <link rel="stylesheet" href="//at.alicdn.com/t/c/font_4263496_xe5w6zp8g5c.css">
